// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqyW-fS6XYBAWOOaJNciI8TULOZTiIlY',
    appId: '1:219375538605:web:2af0d6e6e79fbd74781124',
    messagingSenderId: '219375538605',
    projectId: 'clean-city-app-2df61',
    authDomain: 'clean-city-app-2df61.firebaseapp.com',
    storageBucket: 'clean-city-app-2df61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB564vs86MRn9YscFAPvAQO5ryKND2Ev4c',
    appId: '1:904595105237:android:b7d2fea1380e3d4d00895c',
    messagingSenderId: '904595105237',
    projectId: 'clean-city-app-3602a',
    storageBucket: 'clean-city-app-3602a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCoc_6n2EKSeh47XkKvwkzKXApbOtJ2g',
    appId: '1:904595105237:ios:e3d7dd30a90b680000895c',
    messagingSenderId: '904595105237',
    projectId: 'clean-city-app-3602a',
    storageBucket: 'clean-city-app-3602a.firebasestorage.app',
    iosBundleId: 'com.example.myCleanCity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcqyW-fS6XYBAWOOaJNciI8TULOZTiIlY',
    appId: '1:219375538605:web:7103fb6d9d07c571781124',
    messagingSenderId: '219375538605',
    projectId: 'clean-city-app-2df61',
    authDomain: 'clean-city-app-2df61.firebaseapp.com',
    storageBucket: 'clean-city-app-2df61.firebasestorage.app',
  );
}